### ISSUE TITLE
Does not seems to work with Kirby 3.5.3.1 / PHP 7.4.12

### ISSUE THREAD

**Issue by agloeckner** [HashandSalt/chopper#4]
with chopper I don't get any text from the field, not any error:
`<?= $page->text()->chopper(40) ?>`

without chopper I get the fields text:
`<?= $page->text() ?>`

plugin is in site/plugins/chopper/

any idea?

**Comment by ro-ka** [comment]
I can confirm this also on PHP 8.

**Comment by moevbiz** [comment]
same for me, php 7.4, kirby 3.5.3.1 & 3.5.5, installed chopper via composer, lmk if there's anything else that might be helpful

**Comment by HashandSalt** [comment]
@agloeckner @ro-ka @moevbiz Sorry about the wait! Plugin has been refactored to work with PHP 7.4+. Check the readme for minor breaking changes.
