### ISSUE TITLE
Support for <!--more-->

### ISSUE THREAD

**Issue by joachimesque** [HashandSalt/chopper#5]
Hey, thanks for this plugin!

I'd like to be able to specify when an excerpt should be cut. For example, the following text is chopped just after the start of a new paragraph:

![image](https://user-images.githubusercontent.com/1781070/210569742-71b911b9-cbd9-4bbc-b60f-9d7b131bcfda.png)

With WordPress, Hugo or other CMS, I can add a `<!--more-->` tag which will cut off the escerpt before the limit is reached. Would it be possible to have this feature in Chopper?

Thanks!

**Comment by mauricerenck** [comment]
@joachimesque I just stumbled upon your post here, while looking for something else. I guess you are looking for something like this: https://getkirby.com/docs/cookbook/templating/paginating-posts

I use a very simple page-method for that, where I can set `<!--cut-->` anywhere in my blog posts and everything above that will be shown in the bloglisting as some sort of preview. If you still need that, just ping me, I can give you a snippet.

**Comment by joachimesque** [comment]
Oh nice, I had forgotten about this message and didn’t know about this solution. Thanks!
